version: "3.8"

services:
    palworld-server:
        image: supersunho/palworld-server:latest
        container_name: palworld-server
        hostname: palworld-server
        restart: unless-stopped
        env_file: .env
        # Network configuration
        ports:
            - "8211:8211/udp" # Game server port
            - "27015:27015/udp" # Steam query port
            - "8212:8212/tcp" # REST API port

        # Volume mounts
        volumes:
            - ./palworld_data:/home/steam/palworld_server/Pal/Saved # Game save data
            - ./palworld_backups:/home/steam/backups # Backup storage
            - ./palworld_logs:/home/steam/logs # Application logs
            - /etc/localtime:/etc/localtime:ro # Timezone sync

        # Health check
        healthcheck:
            test: ["CMD", "/usr/local/bin/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5m

        # Resource limits (adjust based on your system)
        deploy:
            resources:
                limits:
                    memory: 8G
                    cpus: "4"
                reservations:
                    memory: 4G
                    cpus: "2"

        # Logging configuration
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "5"
