global:
    smtp_smarthost: "localhost:587"
    smtp_from: "alertmanager@palworld-server.local"

route:
    group_by: ["alertname"]
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 1h
    receiver: "discord-webhook"

receivers:
    - name: "discord-webhook"
      webhook_configs:
          - url: "${DISCORD_WEBHOOK_URL}"
            send_resolved: true
            title: "🚨 Palworld Server Alert"
            text: "{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}"

inhibit_rules:
    - source_match:
          severity: "critical"
      target_match:
          severity: "warning"
      equal: ["alertname", "dev", "instance"]
