# Palworld Dedicated Server Configuration
# Complete configuration with environment variable support
# All settings can be overridden via Docker environment variables

# Core server configuration (basic info only)
server:
    name: "${SERVER_NAME:Palworld Server}"
    password: "${SERVER_PASSWORD:}"
    admin_password: "${ADMIN_PASSWORD:admin123}"
    max_players: ${MAX_PLAYERS:32}
    port: ${SERVER_PORT:8211}
    description: "${SERVER_DESCRIPTION:A Palworld dedicated server}"

# REST API configuration
rest_api:
    enabled: ${REST_API_ENABLED:true}
    port: ${REST_API_PORT:8212}
    host: ${REST_API_HOST:host.docker.internal}

# RCON configuration (fixed missing closing brace)
rcon:
    enabled: ${RCON_ENABLED:true}
    port: ${RCON_PORT:25575}
    host: ${RCON_HOST:host.docker.internal}

# Direct Palworld settings (INI key names for automatic conversion)
palworld_settings:
    # Core server settings
    ServerName: "${SERVER_NAME:Palworld Server}"
    ServerDescription: "${SERVER_DESCRIPTION:A Palworld dedicated server}"
    AdminPassword: "${ADMIN_PASSWORD:admin123}"
    ServerPassword: "${SERVER_PASSWORD:}"
    PublicPort: ${PUBLIC_PORT:8211}
    PublicIP: "${PUBLIC_IP:}"
    ServerPlayerMaxNum: ${SERVER_PLAYER_MAX_NUM:32}
    CoopPlayerMaxNum: ${COOP_PLAYER_MAX_NUM:4}

    # API and RCON settings
    RESTAPIEnabled: ${REST_API_ENABLED:true}
    RESTAPIPort: ${REST_API_PORT:8212}
    RCONEnabled: ${RCON_ENABLED:true}
    RCONPort: ${RCON_PORT:25575}

    # Authentication and region
    bUseAuth: ${B_USE_AUTH:true}
    Region: "${REGION:}"
    BanListURL: "${BANLIST_URL:https://api.palworldgame.com/api/banlist.txt}"

    # Game difficulty and mode
    Difficulty: "${DIFFICULTY:None}"
    bIsMultiplay: ${B_IS_MULTIPLAY:true}
    bIsPvP: ${B_IS_PVP:false}
    bHardcore: ${HARDCORE:false}
    DeathPenalty: "${DEATH_PENALTY:All}"

    # Randomizer settings (new features)
    RandomizerType: "${RANDOMIZER_TYPE:None}"
    RandomizerSeed: "${RANDOMIZER_SEED:}"
    bIsRandomizerPalLevelRandom: ${IS_RANDOMIZER_PAL_LEVEL_RANDOM:false}

    # Time and experience rates
    DayTimeSpeedRate: ${DAY_TIME_SPEED_RATE:1.0}
    NightTimeSpeedRate: ${NIGHT_TIME_SPEED_RATE:1.0}
    ExpRate: ${EXP_RATE:1.0}
    WorkSpeedRate: ${WORK_SPEED_RATE:1.0}

    # Pal settings
    PalCaptureRate: ${PAL_CAPTURE_RATE:1.0}
    PalSpawnNumRate: ${PAL_SPAWN_NUM_RATE:1.0}
    PalDamageRateAttack: ${PAL_DAMAGE_RATE_ATTACK:1.0}
    PalDamageRateDefense: ${PAL_DAMAGE_RATE_DEFENSE:1.0}
    PalStomachDecreaceRate: ${PAL_STOMACH_DECREASE_RATE:1.0}
    PalStaminaDecreaceRate: ${PAL_STAMINA_DECREASE_RATE:1.0}
    PalAutoHPRegeneRate: ${PAL_AUTO_HP_REGENE_RATE:1.0}
    PalAutoHpRegeneRateInSleep: ${PAL_AUTO_HP_REGENE_RATE_IN_SLEEP:1.0}
    PalEggDefaultHatchingTime: ${PAL_EGG_DEFAULT_HATCHING_TIME:72.0}

    # Player settings
    PlayerDamageRateAttack: ${PLAYER_DAMAGE_RATE_ATTACK:1.0}
    PlayerDamageRateDefense: ${PLAYER_DAMAGE_RATE_DEFENSE:1.0}
    PlayerStomachDecreaceRate: ${PLAYER_STOMACH_DECREASE_RATE:1.0}
    PlayerStaminaDecreaceRate: ${PLAYER_STAMINA_DECREASE_RATE:1.0}
    PlayerAutoHPRegeneRate: ${PLAYER_AUTO_HP_REGENE_RATE:1.0}
    PlayerAutoHpRegeneRateInSleep: ${PLAYER_AUTO_HP_REGENE_RATE_IN_SLEEP:1.0}

    # PvP and combat settings
    bEnablePlayerToPlayerDamage: ${B_ENABLE_PLAYER_TO_PLAYER_DAMAGE:false}
    bEnableFriendlyFire: ${B_ENABLE_FRIENDLY_FIRE:false}
    bEnableInvaderEnemy: ${B_ENABLE_INVADER_ENEMY:true}

    # Building and objects
    BuildObjectHpRate: ${BUILD_OBJECT_HP_RATE:1.0}
    BuildObjectDamageRate: ${BUILD_OBJECT_DAMAGE_RATE:1.0}
    BuildObjectDeteriorationDamageRate: ${BUILD_OBJECT_DETERIORATION_DAMAGE_RATE:1.0}
    CollectionDropRate: ${COLLECTION_DROP_RATE:1.0}
    CollectionObjectHpRate: ${COLLECTION_OBJECT_HP_RATE:1.0}
    CollectionObjectRespawnSpeedRate: ${COLLECTION_OBJECT_RESPAWN_SPEED_RATE:1.0}
    bBuildAreaLimit: ${BUILD_AREA_LIMIT:false}
    MaxBuildingLimitNum: ${MAX_BUILDING_LIMIT_NUM:0}
    EnemyDropItemRate: ${ENEMY_DROP_ITEM_RATE:1.0}

    # Base camp settings
    BaseCampMaxNum: ${BASE_CAMP_MAX_NUM:128}
    BaseCampWorkerMaxNum: ${BASE_CAMP_WORKER_MAX_NUM:15}
    BaseCampMaxNumInGuild: ${BASE_CAMP_MAX_NUM_IN_GUILD:4}

    # Guild settings
    GuildPlayerMaxNum: ${GUILD_PLAYER_MAX_NUM:20}
    bAutoResetGuildNoOnlinePlayers: ${B_AUTO_RESET_GUILD_NO_ONLINE_PLAYERS:false}
    AutoResetGuildTimeNoOnlinePlayers: ${AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS:72.0}

    # Items and drops
    DropItemMaxNum: ${DROP_ITEM_MAX_NUM:3000}
    DropItemMaxNum_UNKO: ${DROP_ITEM_MAX_NUM_UNKO:100}
    DropItemAliveMaxHours: ${DROP_ITEM_ALIVE_MAX_HOURS:1.0}
    ItemWeightRate: ${ITEM_WEIGHT_RATE:1.0}
    EquipmentDurabilityDamageRate: ${EQUIPMENT_DURABILITY_DAMAGE_RATE:1.0}

    # Game mechanics
    bActiveUNKO: ${B_ACTIVE_UNKO:false}
    bEnableAimAssistPad: ${B_ENABLE_AIM_ASSIST_PAD:true}
    bEnableAimAssistKeyboard: ${B_ENABLE_AIM_ASSIST_KEYBOARD:false}
    bCanPickupOtherGuildDeathPenaltyDrop: ${B_CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP:false}
    bEnableNonLoginPenalty: ${B_ENABLE_NON_LOGIN_PENALTY:true}
    bEnableFastTravel: ${B_ENABLE_FAST_TRAVEL:true}
    bIsStartLocationSelectByMap: ${B_IS_START_LOCATION_SELECT_BY_MAP:true}
    bExistPlayerAfterLogout: ${B_EXIST_PLAYER_AFTER_LOGOUT:false}
    bEnableDefenseOtherGuildPlayer: ${B_ENABLE_DEFENSE_OTHER_GUILD_PLAYER:false}
    bInvisibleOtherGuildBaseCampAreaFX: ${INVISIBLE_OTHER_GUILD_BASE_CAMP_AREA_FX:false}

    # Save and backup
    AutoSaveSpan: ${AUTO_SAVE_SPAN:30.0}
    bIsUseBackupSaveData: ${IS_USE_BACKUP_SAVE_DATA:true}

    # Chat and communication
    bShowPlayerList: ${SHOW_PLAYER_LIST:false}
    ChatPostLimitPerMinute: ${CHAT_POST_LIMIT_PER_MINUTE:30}

    # Loss and hardcore settings
    bPalLost: ${PAL_LOST:false}
    bCharacterRecreateInHardcore: ${CHARACTER_RECREATE_IN_HARDCORE:false}

    # Logging and monitoring
    LogFormatType: "${LOG_FORMAT_TYPE:Text}"

    # Special events and features
    SupplyDropSpan: ${SUPPLY_DROP_SPAN:180}
    EnablePredatorBossPal: ${ENABLE_PREDATOR_BOSS_PAL:true}

    # Platform settings
    CrossplayPlatforms: "${CROSSPLAY_PLATFORMS:(Steam,Xbox,PS5,Mac)}"

    # Global Palbox settings
    bAllowGlobalPalboxExport: ${ALLOW_GLOBAL_PALBOX_EXPORT:true}
    bAllowGlobalPalboxImport: ${ALLOW_GLOBAL_PALBOX_IMPORT:false}

    # Network settings
    ServerReplicatePawnCullDistance: ${SERVER_REPLICATE_PAWN_CULL_DISTANCE:15000.0}
    ItemContainerForceMarkDirtyInterval: ${ITEM_CONTAINER_FORCE_MARK_DIRTY_INTERVAL:1.0}

# Monitoring and metrics configuration
monitoring:
    mode: "${MONITORING_MODE:logs}"
    log_level: "${LOG_LEVEL:INFO}"
    metrics_interval: ${METRICS_INTERVAL:60}
    enable_dashboard: ${ENABLE_DASHBOARD:true}
    dashboard_port: ${DASHBOARD_PORT:8080}

# Backup system configuration
backup:
    enabled: ${BACKUP_ENABLED:true}
    interval_seconds: ${BACKUP_INTERVAL:3600}
    retention_days: ${BACKUP_RETENTION_DAYS:7}
    retention_weeks: ${BACKUP_RETENTION_WEEKS:4}
    retention_months: ${BACKUP_RETENTION_MONTHS:6}
    compress: ${BACKUP_COMPRESS:true}
    max_backups: ${BACKUP_MAX_COUNT:100}
    cleanup_interval: ${BACKUP_CLEANUP_INTERVAL:86400}

# Discord notification configuration
discord:
    webhook_url: "${DISCORD_WEBHOOK_URL:}"
    enabled: ${DISCORD_ENABLED:false}
    mention_role: "${DISCORD_MENTION_ROLE:}"
    events:
        server_start: ${DISCORD_EVENT_START:true}
        server_stop: ${DISCORD_EVENT_STOP:true}
        player_join: ${DISCORD_EVENT_JOIN:true}
        player_leave: ${DISCORD_EVENT_LEAVE:true}
        backup_complete: ${DISCORD_EVENT_BACKUP:true}
        errors: ${DISCORD_EVENT_ERRORS:true}

# Directory path configuration
paths:
    server_dir: "${SERVER_DIR:/home/steam/palworld_server}"
    backup_dir: "${BACKUP_DIR:/home/steam/backups}"
    log_dir: "${LOG_DIR:/home/steam/logs}"
    steamcmd_dir: "${STEAMCMD_DIR:/home/steam/steamcmd}"

# SteamCMD configuration
steamcmd:
    app_id: 2394010
    validate: ${STEAMCMD_VALIDATE:true}
    auto_update: ${AUTO_UPDATE:true}
    update_on_start: ${UPDATE_ON_START:true}

# Engine.ini performance configuration
engine:
    lan_server_max_tick_rate: ${ENGINE_LAN_TICK_RATE:120}
    net_server_max_tick_rate: ${ENGINE_NET_TICK_RATE:120}
    configured_internet_speed: ${ENGINE_INTERNET_SPEED:104857600}
    configured_lan_speed: ${ENGINE_LAN_SPEED:104857600}
    max_client_rate: ${ENGINE_MAX_CLIENT_RATE:104857600}
    max_internet_client_rate: ${ENGINE_MAX_INTERNET_CLIENT_RATE:104857600}
    smooth_frame_rate: ${ENGINE_SMOOTH_FRAME_RATE:true}
    use_fixed_frame_rate: ${ENGINE_USE_FIXED_FRAME_RATE:false}
    min_desired_frame_rate: ${ENGINE_MIN_FRAME_RATE:60.0}
    fixed_frame_rate: ${ENGINE_FIXED_FRAME_RATE:120.0}
    net_client_ticks_per_second: ${ENGINE_CLIENT_TICKS:120}
    frame_rate_lower_bound: ${ENGINE_FRAME_RATE_LOWER:30.0}
    frame_rate_upper_bound: ${ENGINE_FRAME_RATE_UPPER:120.0}
