language: ${LANGUAGE:ko}

server:
    name: "${SERVER_NAME:Palworld Server}"
    password: "${SERVER_PASSWORD:}"
    admin_password: "${ADMIN_PASSWORD:admin123}"
    max_players: ${MAX_PLAYERS:32}
    port: ${SERVER_PORT:8211}
    description: "${SERVER_DESCRIPTION:A Palworld dedicated server}"

rest_api:
    enabled: ${RESTAPI_ENABLED:true}
    port: ${RESTAPI_PORT:8212}
    host: ${RESTAPI_HOST:localhost}

rcon:
    enabled: ${RCON_ENABLED:true}
    port: ${RCON_PORT:25575}
    host: ${RCON_HOST:localhost}

server_startup:
    use_performance_threads: ${USE_PERFORMANCE_THREADS:true}
    disable_async_loading: ${DISABLE_ASYNC_LOADING:true}
    use_multithread_for_ds: ${USE_MULTITHREAD_FOR_DS:true}
    query_port: ${QUERY_PORT:27018}
    enable_public_lobby: ${ENABLE_PUBLIC_LOBBY:false}
    log_format: ${LOG_FORMAT:text}
    worker_threads_count: ${WORKER_THREADS_COUNT:0}
    additional_options: "${ADDITIONAL_SERVER_OPTIONS:}"

palworld_settings:
    AdminPassword: "${ADMIN_PASSWORD:admin123}"
    CoopPlayerMaxNum: ${COOP_PLAYER_MAX_NUM:4}
    PublicIP: "${PUBLIC_IP:}"
    PublicPort: ${PUBLIC_PORT:8211}
    ServerDescription: "${SERVER_DESCRIPTION:A Palworld dedicated server}"
    ServerName: "${SERVER_NAME:Default Palworld Server}"
    ServerPassword: "${SERVER_PASSWORD:}"
    ServerPlayerMaxNum: ${SERVER_PLAYER_MAX_NUM:32}

    RCONEnabled: ${RCON_ENABLED:true}
    RCONPort: ${RCON_PORT:25575}
    RESTAPIEnabled: ${RESTAPI_ENABLED:true}
    RESTAPIPort: ${RESTAPI_PORT:8212}

    BanListURL: "${BAN_LIST_URL:https://api.palworldgame.com/api/banlist.txt}"
    Region: "${REGION:}"
    bUseAuth: ${USE_AUTH:true}

    DeathPenalty: "${DEATH_PENALTY:All}"
    Difficulty: "${DIFFICULTY:None}"
    bHardcore: ${HARDCORE:false}
    bIsMultiplay: ${IS_MULTIPLAY:false}
    bIsPvP: ${IS_PVP:false}

    RandomizerSeed: "${RANDOMIZER_SEED:}"
    RandomizerType: "${RANDOMIZER_TYPE:None}"
    bIsRandomizerPalLevelRandom: ${IS_RANDOMIZER_PAL_LEVEL_RANDOM:false}

    DayTimeSpeedRate: ${DAY_TIME_SPEED_RATE:1.0}
    ExpRate: ${EXP_RATE:1.0}
    NightTimeSpeedRate: ${NIGHT_TIME_SPEED_RATE:1.0}
    WorkSpeedRate: ${WORK_SPEED_RATE:1.0}

    PalAutoHPRegeneRate: ${PAL_AUTO_HP_REGENE_RATE:1.0}
    PalAutoHpRegeneRateInSleep: ${PAL_AUTO_HP_REGENE_RATE_IN_SLEEP:1.0}
    PalCaptureRate: ${PAL_CAPTURE_RATE:1.0}
    PalDamageRateAttack: ${PAL_DAMAGE_RATE_ATTACK:1.0}
    PalDamageRateDefense: ${PAL_DAMAGE_RATE_DEFENSE:1.0}
    PalEggDefaultHatchingTime: ${PAL_EGG_DEFAULT_HATCHING_TIME:72.0}
    PalSpawnNumRate: ${PAL_SPAWN_NUM_RATE:1.0}
    PalStaminaDecreaceRate: ${PAL_STAMINA_DECREACE_RATE:1.0}
    PalStomachDecreaceRate: ${PAL_STOMACH_DECREACE_RATE:1.0}

    PlayerAutoHPRegeneRate: ${PLAYER_AUTO_HP_REGENE_RATE:1.0}
    PlayerAutoHpRegeneRateInSleep: ${PLAYER_AUTO_HP_REGENE_RATE_IN_SLEEP:1.0}
    PlayerDamageRateAttack: ${PLAYER_DAMAGE_RATE_ATTACK:1.0}
    PlayerDamageRateDefense: ${PLAYER_DAMAGE_RATE_DEFENSE:1.0}
    PlayerStaminaDecreaceRate: ${PLAYER_STAMINA_DECREACE_RATE:1.0}
    PlayerStomachDecreaceRate: ${PLAYER_STOMACH_DECREACE_RATE:1.0}

    bEnableFriendlyFire: ${ENABLE_FRIENDLY_FIRE:false}
    bEnableInvaderEnemy: ${ENABLE_INVADER_ENEMY:true}
    bEnablePlayerToPlayerDamage: ${ENABLE_PLAYER_TO_PLAYER_DAMAGE:false}

    BuildObjectDamageRate: ${BUILD_OBJECT_DAMAGE_RATE:1.0}
    BuildObjectDeteriorationDamageRate: ${BUILD_OBJECT_DETERIORATION_DAMAGE_RATE:1.0}
    BuildObjectHpRate: ${BUILD_OBJECT_HP_RATE:1.0}
    CollectionDropRate: ${COLLECTION_DROP_RATE:1.0}
    CollectionObjectHpRate: ${COLLECTION_OBJECT_HP_RATE:1.0}
    CollectionObjectRespawnSpeedRate: ${COLLECTION_OBJECT_RESPAWN_SPEED_RATE:1.0}
    EnemyDropItemRate: ${ENEMY_DROP_ITEM_RATE:1.0}
    MaxBuildingLimitNum: ${MAX_BUILDING_LIMIT_NUM:0}
    bBuildAreaLimit: ${BUILD_AREA_LIMIT:false}

    BaseCampMaxNum: ${BASE_CAMP_MAX_NUM:128}
    BaseCampMaxNumInGuild: ${BASE_CAMP_MAX_NUM_IN_GUILD:4}
    BaseCampWorkerMaxNum: ${BASE_CAMP_WORKER_MAX_NUM:15}

    AutoResetGuildTimeNoOnlinePlayers: ${AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS:72.0}
    GuildPlayerMaxNum: ${GUILD_PLAYER_MAX_NUM:20}
    bAutoResetGuildNoOnlinePlayers: ${AUTO_RESET_GUILD_NO_ONLINE_PLAYERS:false}

    DropItemAliveMaxHours: ${DROP_ITEM_ALIVE_MAX_HOURS:1.0}
    DropItemMaxNum: ${DROP_ITEM_MAX_NUM:3000}
    DropItemMaxNum_UNKO: ${DROP_ITEM_MAX_NUM_UNKO:100}
    EquipmentDurabilityDamageRate: ${EQUIPMENT_DURABILITY_DAMAGE_RATE:1.0}
    ItemWeightRate: ${ITEM_WEIGHT_RATE:1.0}

    bActiveUNKO: ${ACTIVE_UNKO:false}
    bCanPickupOtherGuildDeathPenaltyDrop: ${CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP:false}
    bEnableAimAssistKeyboard: ${ENABLE_AIM_ASSIST_KEYBOARD:false}
    bEnableAimAssistPad: ${ENABLE_AIM_ASSIST_PAD:true}
    bEnableDefenseOtherGuildPlayer: ${ENABLE_DEFENSE_OTHER_GUILD_PLAYER:false}
    bEnableFastTravel: ${ENABLE_FAST_TRAVEL:true}
    bEnableNonLoginPenalty: ${ENABLE_NON_LOGIN_PENALTY:true}
    bExistPlayerAfterLogout: ${EXIST_PLAYER_AFTER_LOGOUT:false}
    bInvisibleOtherGuildBaseCampAreaFX: ${INVISIBLE_OTHER_GUILD_BASE_CAMP_AREA_FX:false}
    bIsStartLocationSelectByMap: ${IS_START_LOCATION_SELECT_BY_MAP:true}

    AutoSaveSpan: ${AUTO_SAVE_SPAN:30.0}
    bIsUseBackupSaveData: ${IS_USE_BACKUP_SAVE_DATA:true}

    ChatPostLimitPerMinute: ${CHAT_POST_LIMIT_PER_MINUTE:30}
    bShowPlayerList: ${SHOW_PLAYER_LIST:false}

    bCharacterRecreateInHardcore: ${CHARACTER_RECREATE_IN_HARDCORE:false}
    bPalLost: ${PAL_LOST:false}

    LogFormatType: "${LOG_FORMAT_TYPE:Text}"

    EnablePredatorBossPal: ${ENABLE_PREDATOR_BOSS_PAL:true}
    SupplyDropSpan: ${SUPPLY_DROP_SPAN:180}

    CrossplayPlatforms: "${CROSSPLAY_PLATFORMS:(Steam,Xbox,PS5,Mac)}"

    bAllowGlobalPalboxExport: ${ALLOW_GLOBAL_PALBOX_EXPORT:true}
    bAllowGlobalPalboxImport: ${ALLOW_GLOBAL_PALBOX_IMPORT:false}

    ItemContainerForceMarkDirtyInterval: ${ITEM_CONTAINER_FORCE_MARK_DIRTY_INTERVAL:1.0}
    ServerReplicatePawnCullDistance: ${SERVER_REPLICATE_PAWN_CULL_DISTANCE:15000.0}

monitoring:
    mode: "${MONITORING_MODE:logs}"
    log_level: "${LOG_LEVEL:INFO}"
    metrics_interval: ${METRICS_INTERVAL:60}
    enable_dashboard: ${ENABLE_DASHBOARD:true}
    dashboard_port: ${DASHBOARD_PORT:8080}
    log_format_style: "${LOG_FORMAT_STYLE:simple}"
    idle_restart:
        enabled: ${IDLE_RESTART_ENABLED:true}
        idle_minutes: ${IDLE_RESTART_MINUTES:30}

backup:
    enabled: ${BACKUP_ENABLED:true}
    interval_seconds: ${BACKUP_INTERVAL:3600}
    retention_days: ${BACKUP_RETENTION_DAYS:7}
    retention_weeks: ${BACKUP_RETENTION_WEEKS:4}
    retention_months: ${BACKUP_RETENTION_MONTHS:6}
    compress: ${BACKUP_COMPRESS:true}
    max_backups: ${BACKUP_MAX_COUNT:100}
    cleanup_interval: ${BACKUP_CLEANUP_INTERVAL:86400}

discord:
    webhook_url: "${DISCORD_WEBHOOK_URL:}"
    enabled: ${DISCORD_ENABLED:false}
    mention_role: "${DISCORD_MENTION_ROLE:}"
    events:
        server_start: ${DISCORD_EVENT_START:true}
        server_stop: ${DISCORD_EVENT_STOP:true}
        player_join: ${DISCORD_EVENT_JOIN:true}
        player_leave: ${DISCORD_EVENT_LEAVE:true}
        backup_complete: ${DISCORD_EVENT_BACKUP:true}
        errors: ${DISCORD_EVENT_ERRORS:true}
        idle_restart: ${DISCORD_EVENT_IDLE_RESTART:true}

paths:
    server_dir: "${SERVER_DIR:/home/steam/palworld_server}"
    backup_dir: "${BACKUP_DIR:/home/steam/backups}"
    log_dir: "${LOG_DIR:/home/steam/logs}"
    steamcmd_dir: "${STEAMCMD_DIR:/home/steam/steamcmd}"

steamcmd:
    app_id: 2394010
    validate: ${STEAMCMD_VALIDATE:true}
    auto_update: ${AUTO_UPDATE:true}
    update_on_start: ${UPDATE_ON_START:true}

engine:
    lan_server_max_tick_rate: ${ENGINE_LAN_TICK_RATE:120}
    net_server_max_tick_rate: ${ENGINE_NET_TICK_RATE:120}
    configured_internet_speed: ${ENGINE_INTERNET_SPEED:104857600}
    configured_lan_speed: ${ENGINE_LAN_SPEED:104857600}
    max_client_rate: ${ENGINE_MAX_CLIENT_RATE:104857600}
    max_internet_client_rate: ${ENGINE_MAX_INTERNET_CLIENT_RATE:104857600}
    smooth_frame_rate: ${ENGINE_SMOOTH_FRAME_RATE:true}
    use_fixed_frame_rate: ${ENGINE_USE_FIXED_FRAME_RATE:false}
    min_desired_frame_rate: ${ENGINE_MIN_FRAME_RATE:60.0}
    fixed_frame_rate: ${ENGINE_FIXED_FRAME_RATE:120.0}
    net_client_ticks_per_second: ${ENGINE_CLIENT_TICKS:120}
    frame_rate_lower_bound: ${ENGINE_FRAME_RATE_LOWER:30.0}
    frame_rate_upper_bound: ${ENGINE_FRAME_RATE_UPPER:120.0}
