{{- if not .Values.server.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "palworld-server.fullname" . }}-password
  labels:
    app: {{ include "palworld-server.name" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.server.adminPasswordKey }}: {{ .Values.server.adminPassword | default (randAlphaNum 24) | quote }}
{{- end }}
