# yaml-language-server: $schema=https://json.schemastore.org/grafana-datasource.json
# Grafana datasource configuration
apiVersion: 1

datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true
      basicAuth: false
      jsonData:
          timeInterval: "60s"
          queryTimeout: "300s"
