# yaml-language-server: $schema=https://json.schemastore.org/grafana-datasource.json

apiVersion: 1
datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      isDefault: true
      editable: true
      basicAuth: false
      jsonData:
          timeInterval: "60s"
          queryTimeout: "300s"
          httpMethod: GET
      version: 1
